### PR TITLE
Add the message handling JS to the oEmbed response

### PR DESCRIPTION
**Pull request by pento**
See #116.

### CODE REVIEW

**Comment by pento** [comment]
The remaining unit test errors are kind of annoying. the `&&` in the JS is being converted to `&` when it's encoded to XML, instead of being converted to `&amp;&amp;`, as we want. Perhaps we should be looking at `htmlentities()`, instead?

**Comment by swissspidy** [comment]
Or CDATA for simplicity?

**Comment by pento** [comment]
It didn't work properly when I gave it a quick try, but I probably messed it up. :) I'll try it again.

**Comment by pfefferle** [comment]
I think CDATA is not a good idea, because the spec proposes PCDATA:

> The key-value pairs to be returned are specified below. All text must be UTF-8 encoded. Values should be escaped PCDATA.

**Comment by swissspidy** [comment]
@pfefferle Thanks for chiming in! We should follow the spec in that case.

**Pull request merged**
