### PR TITLE
Remove word count from excerpt

### LINKED ISSUE #130: Indicating word count in the excerpt
Why is it helpful to include the word count? It seems out of place.

### PR DESCRIPTION
**Pull request by swissspidy**
This would fix #130, but I'm skeptical.

### CODE REVIEW

**Comment by pento** [comment]
If we're going to change it, I'd be inclined to make it a "Read more..." string, kind of like what Facebook does for long status updates.

**Comment by danielbachhuber** [comment]
> I'd be inclined to make it a "Read more..." string, kind of like what Facebook does for long status updates.

:+1: Read more

**Comment by swissspidy** [comment]
Here's how it looks with "Read more…":

screen shot 2015-09-25 at 08 34 11

**Comment by swissspidy** [comment]
@melchoyce What's your opinion on this?

**Comment by melchoyce** [comment]
It feels abrupt without an ellipses — I'd keep that in. I'm fine with dropping the word count, like:

" ... Read More"

**Pull request merged**
