### PR TITLE
Delete two backsticks from the height calculation lines

### PR DESCRIPTION
**Pull request by FlorianBrinkmann**

### CODE REVIEW

**Comment by swissspidy** [comment]
Oops, how could I miss this! My editor didn't throw a warning either.

can you also remove that spacing before the two commas? Will merge right away then.

**Comment by FlorianBrinkmann** [comment]
Done

**Comment by kanenas** [comment]
@swissspidy, sorry I am a little bit confused. Is this in the https://wordpress.org/plugins/oembed-api/changelog/ 0.7.0-20150915 release?

**Comment by swissspidy** [comment]
@kanenas You can ignore the version numbers. Every commit on GitHub gets automatically synched to WordPress.org. So if you click "Download Version 0.7.0-20150915" now, this change will be already included.

**Comment by FlorianBrinkmann** [comment]
@swissspidy I get a 404 when I try to download the zip of the latest version here: https://wordpress.org/plugins/oembed-api/developers/

**Comment by swissspidy** [comment]
@FlorianBrinkmann The latest version is always available at https://downloads.wordpress.org/plugin/oembed-api.zip. Click the big orange download button :)

**Comment by kanenas** [comment]
@swissspidy, something is mixed up! I just downloaded this https://downloads.wordpress.org/plugin/oembed-api.zip and I can still see <strong>backticks</strong> in ``includes/template.php``

**Comment by FlorianBrinkmann** [comment]
I can confirm that

**Comment by FlorianBrinkmann** [comment]
Something didn't work with the merge: https://github.com/swissspidy/oEmbed-API/blob/master/includes/template.php#L305

**Comment by swissspidy** [comment]
Ah, I didn't see that you created your pull request off the `76-iframe-height` branch, that's why the fix wasn't merged into `master`... I manually committed it now.

**Comment by FlorianBrinkmann** [comment]
Oops, I thought that would be the right way, sorry :)

**Pull request merged**
