### PR TITLE
Add title attribute, shown as a tooltip text when the mouse moves over the element

### PR DESCRIPTION
**Pull request by kanenas**

### CODE REVIEW

**Comment by ntwb** [comment]
Is this needed? We've been removing "title attributes" from core, see [#24766](https://core.trac.wordpress.org/ticket/24766)

**Comment by swissspidy** [comment]
Having the same concern as @ntwb, especially since the title attribute is the same as the link text.

**Comment by kanenas** [comment]
@ntwb & @swissspidy, thank you for your insight.

<strong>TITLE</strong> attribute usage:
* use it for your users, not search engines (this approach always pays back)
* don’t duplicate it with link text (this hurts usability: for example some blind users will hear the same text twice)
* don’t put too much weight on the title attributes as not all screen readers may render it (make sure either surrounding text or anchor text explains the link at least the first time you use it).

So, I guess you are right in most cases.

<strong>Suggestion</strong>: I think here...
```php
	<div class="wp-embed-social">
		<?php if ( get_comments_number( $post->ID ) || comments_open( $post->ID ) ) : ?>
			<div class="wp-embed-comments">
				<a href="<?php echo esc_url( get_comments_link( $post->ID ) ); ?>" target="_top">
					<span class="dashicons dashicons-admin-comments"></span>
					<?php
					printf(
						_n(
							'%s <span class="screen-reader-text">Comment</span>',
							'%s <span class="screen-reader-text">Comments</span>',
							get_comments_number( $post->ID ),
							'oembed-api'
						),
						get_comments_number( $post->ID )
					);
					?>
				</a>
			</div>
		<?php endif; ?>
		<div class="wp-embed-share">
			<button type="button" class="wp-embed-share-dialog-open" aria-label="<?php _e( 'Open sharing dialog', 'oembed-api' ); ?>">
				<span class="dashicons dashicons-share"></span>
			</button>
		</div>
	</div>
```
could be useful. What do you think?

**Comment by swissspidy** [comment]
Quoting @DrewAPicture's [comment](https://core.trac.wordpress.org/ticket/32095#comment:4) regarding the removal of the title attribute in the link dialog:

> In recent years, we've begun to actively discourage the use of title attributes in links as they are largely useless outside of providing the "hover tooltip" many visual users enjoy, and more importantly, they don't promote good accessibility.

To re-iterate on the accessibility part: Screen readers ignore the title attribute.

**Pull request closed without merging**
